### ISSUE TITLE
NullPointerException in JointPrivilegedConfigurationHandler

### ISSUE THREAD

**Issue by allspawj** [ihmcrobotics/ihmc-open-robotics-software#42]
In JointPrivilegedConfigurationHandler.java the function submitPrivilegedConfigurationCommand there is a nullpointer exception, I have traced it to ~line 159
int jointIndex = jointIndices.get(joint).intValue(); 

I added a print

if(jointIndices.get(joint) == null)
        	 System.err.println("JOINT INDICES IS NULL " + joint.getName());

Which prints out leftForearmYaw. Is leftForearmYaw even a joint we are supposed to be able to move?

Full exception
[ERROR] [1466027433.206373074]: Exception in thread "Thread-6" java.lang.RuntimeException: java.lang.NullPointerException
[ERROR] [1466027433.206484247]:         at us.ihmc.wholeBodyController.DRCControllerThread.run(DRCControllerThread.java:347)
[ERROR] [1466027433.206575785]:         at us.ihmc.wholeBodyController.concurrent.MultiThreadedRealTimeRobotController$MultiThreadedRobotControlElementRunner.run(MultiThreadedRealTimeRobotController.java:79)
[ERROR] [1466027433.206648428]:         at us.ihmc.realtime.RealtimeThread.runFromNative(RealtimeThread.java:133)
[ERROR] [1466027433.206813253]: Caused by: java.lang.NullPointerException
[ERROR] [1466027433.206926639]:         at us.ihmc.commonWalkingControlModules.inverseKinematics.JointPrivilegedConfigurationHandler.submitPrivilegedConfigurationCommand(JointPrivilegedConfigurationHandler.java:164)
[ERROR] [1466027433.207017935]:         at us.ihmc.commonWalkingControlModules.momentumBasedController.optimization.MotionQPInputCalculator.updatePrivilegedConfiguration(MotionQPInputCalculator.java:131)
[ERROR] [1466027433.207114014]:         at us.ihmc.commonWalkingControlModules.momentumBasedController.optimization.InverseDynamicsOptimizationControlModule.submitPrivilegedConfigurationCommand(InverseDynamicsOptimizationControlModule.java:276)
[ERROR] [1466027433.207202409]:         at us.ihmc.commonWalkingControlModules.controllerCore.WholeBodyInverseDynamicsSolver.submitInverseDynamicsCommandList(WholeBodyInverseDynamicsSolver.java:216)
[ERROR] [1466027433.207282803]:         at us.ihmc.commonWalkingControlModules.controllerCore.WholeBodyControllerCore.submitControllerCoreCommand(WholeBodyControllerCore.java:87)
[ERROR] [1466027433.207365684]:         at us.ihmc.commonWalkingControlModules.highLevelHumanoidControl.HighLevelHumanoidControllerManager.doControl(HighLevelHumanoidControllerManager.java:174)
[ERROR] [1466027433.207441665]:         at us.ihmc.simulationconstructionset.robotController.ModularRobotController.doControl(ModularRobotController.java:20)
[ERROR] [1466027433.207512246]:         at us.ihmc.wholeBodyController.DRCControllerThread.run(DRCControllerThread.java:339)

**Comment by allspawj** [comment]
To add to this, if you just disreguard the null joints and continue, the full list of joints that show up as null is 
leftForearmYaw
leftWristRoll
leftWristPitch

rightForearmYaw
rightWristRoll
rightWristPitch

Is there some config file we can disable these temporarily? @dljsjr
